### PR TITLE
Adds rotation_with_offset

### PR DESCRIPTION
**Pull request by hitormiss**
Adds a function to rotate around an offset point (and the accompany changes to other functions and the FContext structure.

### CODE REVIEW

**Comment by jrmobley** [comment]
Could you explain a little about your use case?  I am thinking of moving the `advance` parameter into the `FContext` as a state variable, since it performs a very similar function (being an offset that is applied before the rotation).  But I note that in your implementation, the offset is applied _after_ the scale factor, so I wanted to understand that choice.

**Comment by hitormiss** [comment]
I added the function for a Mickey Mouse analog watchface I'm working on, so that I could rotate around the pivot point of the minute & hour hands.  I want the user to be able to choose a small, medium, or large Mickey and adjust the hands accordingly (so the scaling is applied after the offset).

**Comment by jrmobley** [comment]
Haven't forgotten about this.  Should be able to make equivalent changes soon and update the package.

**Comment by jrmobley** [comment]
I added a pivot point property to the FContext.  This is not the same math as the PR, but it implements pivot point functionality as I understand it.  Also rebuilt the test app to use SVG paths for hour and minute hands, which is effectively the same use case that motivated the PR.

**Pull request closed without merging**
